# you can use `ros2 launch ur_robotiq_moveit_config view_ur_robotiq.launch.py`
# to help you find the desired joint angles
initial_positions:
  shoulder_pan_joint: 0.0
  shoulder_lift_joint: -1.57
  elbow_joint: 1.57
  wrist_1_joint: -1.57
  wrist_2_joint: -1.57
  wrist_3_joint: 0.0